FROM martinez/meteor-apline

MAINTAINER Martin Bucko <bucko@treecom.net>

ENV NODE_ENV=production

# If your project need phantomjs
# RUN sh $METEORD_DIR/install_phantomjs.sh

# If your project need graficmagic
# RUN sh $METEORD_DIR/install_graphicsmagick.sh

# Feel free to add other preconfigured build steps to repository. Thanks!